force-app/main/default/objects/SF_Training_Topic__c/SF_Training_Topic__c.object-meta.xml
<CustomObject>
    <label>SF Training Topic</label>
    <nameField>
        <displayFormat>SF-{0000}</displayFormat>
        <label>SF Training Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF Training Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SF_Training_Topic__c/fields/Topic_Category__c.field-meta.xml
<CustomField>
    <fullName>Topic_Category__c</fullName>
    <label>Topic Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Javascript</fullName>
            </value>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SF_Training_Topic__c/fields/Topic_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Name__c</fullName>
    <label>Topic Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SFTopicHelper.cls
public with sharing class SFTopicHelper {
  

    @AuraEnabled(cacheable=true)
    public static List<SF_Training_Topic__c> getSFTrainingTopics() {

        return [SELECT ID,Topic_Name__c, Topic_Category__c FROM SF_Training_Topic__c WITH SECURITY_ENFORCED];
        
    }
    @AuraEnabled(cacheable=true)
    public static List<SF_Training_Topic__c> getSFTrainingTopicsByCategory(string strCat) {

        strCat = strCat + '%';
        return [SELECT ID,Topic_Name__c, Topic_Category__c FROM SF_Training_Topic__c WHERE
                Topic_Category__c  like :strCat WITH SECURITY_ENFORCED];
        
    }
}